name: docker-buildx

on:
  watch:
    types: [started]

env:
  DOCKERHUB_USER: wiserain
  DOCKERHUB_REPO: rclone

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=version::$(curl -q https://downloads.rclone.org/version.txt | cut -d'v' -f 2)
          echo ::set-output name=github_desc::$(curl -sX GET https://api.github.com/repos/wiserain/docker-rclone | jq -r .description)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest,${{ steps.vars.outputs.version }}
          dockerFile: Dockerfile
          buildArg: RCLONE_VER=${{ steps.vars.outputs.version }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          destination_container_repo: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          provider: dockerhub
          short_description: ${{ steps.vars.outputs.github_desc }}
          readme_file: 'README.md'
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest, ${{ steps.vars.outputs.version }}
