name: docker-buildx

on:
  watch:
    types: [started]

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=buildx_platforms::linux/amd64,linux/arm/v7,linux/arm64
          echo ::set-output name=dockerhub_user::wiserain
          echo ::set-output name=dockerhub_repo::rclone
          echo ::set-output name=version::$(curl -q https://downloads.rclone.org/version.txt | cut -d'v' -f 2)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Dockerhub Login
        env:
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${{ steps.vars.outputs.dockerhub_user }}" --password-stdin
      -
        name: Setup Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - 
        name: Run Buildx
        env:
          IMAGE_NAME: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform ${{ steps.vars.outputs.buildx_platforms }} \
            --tag "${IMAGE_NAME}:${{ steps.vars.outputs.version }}" \
            --tag "${IMAGE_NAME}:latest" \
            --file Dockerfile . \
            --build-arg "RCLONE_VER=${{ steps.vars.outputs.version }}"
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ steps.vars.outputs.dockerhub_user }}/${{ steps.vars.outputs.dockerhub_repo }}
            Tags: latest, ${{ steps.vars.outputs.version }}
